### ISSUE TITLE
TYPO3 Caching problems domain model

### ISSUE THREAD

**Issue by KillerDose** [cyberhouse/news_importicsxml#4]
I have news_importicsxml 1.0.2 installed on TYPO3 6.2.25. We use news 3.2.4.

When I trigger my schedule I get the following exception:

`Parse error: parse error, expecting "function (T_FUNCTION)" in .../typo3temp/Cache/Code/news/tx_news_domain_model_news.php on line 1519`

When change lines 5 and 6 in `Classes\Domain\Model\News.php` from

`class News extends \GeorgRinger\News\Domain\Model\News
{`

to
`class News extends \GeorgRinger\News\Domain\Model\News {`

I can resolve this error. There is a Caching problem. In the auto-generated file `typo3temp\Cache\news\tx_news_domain_model_news.php` there is one bracket too much when the Code is formatted as in current code.

![tx_news_domain_model_news.php](https://cloud.githubusercontent.com/assets/20813251/19768613/8b20c034-9c58-11e6-884b-64271a2d097a.png)

Do you have any experience with that issue? Please let me know if I can send you a pull request on that.

**Comment by georgringer** [comment]
closing issue because outdated, solved in meantime
