### ISSUE TITLE
No scheduler task available when installed with EM

### ISSUE THREAD

**Issue by sebkln** [cyberhouse/news_importicsxml#5]
I have tried to install the current version of _news_importicsxml_ with the Extension Manager in both TYPO3 7.6 and 8.7. There is no scheduler task found, neither in submodule "Information" nor in the class list of a new scheduler task.
Actually, there is a new row under "Information", but every text is missing. The _new task_ button on the right works, but the class is missing. When trying to execute the new task, the following error occurs:

> Execution of task " ()" failed with the following message: TYPO3 Fatal Error: Extension key "" is NOT loaded! 

To verificate the problem, I installed the extension using `composer require georgringer/news-importicsxml` in an TYPO3 7.6 instance. The scheduler task was available immediately.

Also, the new tab "Extended" is missing in news records when installed through EM. Again, in composer-mode everything is seems to be working fine.

Can someone confirm this issue?

**Comment by georgringer** [comment]
please use https://github.com/georgringer/news_importicsxml as I doubt that this repository is maintained
